# Generated by Django 5.0.4 on 2024-05-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_productfeature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='features.feature'),
        ),
    ]
