# Generated by Django 5.0.4 on 2024-05-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_featurevalue_feature'),
        ('products', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='feature_value',
            field=models.ManyToManyField(related_name='product_features', to='features.featurevalue'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product'),
        ),
    ]
